spring:
  cloud:
    config:
      server:
        vault:
          authentication: token
          token: "00000000-0000-0000-0000-000000000000"
          kv-version: 2
          default-key: ${spring.application.name}
